# Generated by Django 5.0.1 on 2025-06-05 14:48

import front.models
import secured_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='メールアドレス')),
                ('verify_token', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='UUID')),
                ('app_settings_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='アプリ申請URL')),
                ('is_submitted', models.BooleanField(default=0, verbose_name='2段階目申請送信済み')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='お名前・法人名')),
                ('website_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='公式サイト URL')),
                ('x_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='X（旧Twitter）')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube')),
                ('ticktock', models.CharField(blank=True, max_length=255, null=True, verbose_name='ticktock')),
                ('followers_count', models.IntegerField(blank=True, null=True, verbose_name='総フォロワー数')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考欄')),
                ('other_sns', models.JSONField(blank=True, default=list, null=True, verbose_name='その他のSNS')),
                ('app_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='希望するアプリ名（仮）')),
                ('subscription_enabled', models.BooleanField(default=0, verbose_name='月額有料会員プランの追加')),
                ('subscription_price', models.IntegerField(blank=True, null=True, verbose_name='月額有料会員の金額')),
                ('app_color', models.IntegerField(default=0, verbose_name='初期のアプリカラー')),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to=front.models.path_and_rename, verbose_name='アプリアイコン画像')),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to=front.models.path_and_rename, verbose_name='ロゴ画像')),
                ('naming_enabled', models.BooleanField(default=0, verbose_name='コンテンツの呼称変更の希望')),
                ('home_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='ホーム（ヘッダー）')),
                ('home_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home（フッター）')),
                ('shop_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='ショップ（ヘッダー）')),
                ('shop_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop（フッター）')),
                ('timeline_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='タイムライン（ヘッダー）')),
                ('timeline_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='TL（フッター）')),
                ('chat_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='チャット（ヘッダー）')),
                ('chat_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chat（フッター）')),
                ('more_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='More')),
                ('more_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='More（フッター）')),
                ('collection', models.CharField(blank=True, max_length=255, null=True, verbose_name='コレクション')),
                ('pickup', models.CharField(blank=True, max_length=255, null=True, verbose_name='ピックアップ')),
                ('goods', models.CharField(blank=True, max_length=255, null=True, verbose_name='グッズ')),
                ('products', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品')),
                ('twoshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='2shot')),
                ('live', models.CharField(blank=True, max_length=255, null=True, verbose_name='ライブ')),
                ('room', models.CharField(blank=True, max_length=255, null=True, verbose_name='ルーム')),
                ('dm_long', models.CharField(blank=True, max_length=255, null=True, verbose_name='ダイレクトメッセージ')),
                ('dm_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='DM')),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='アーティストの呼称')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='銀行名')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='銀行支店名')),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='銀行支店コード')),
                ('bank_account_number', secured_fields.fields.EncryptedCharField(blank=True, max_length=30, null=True, verbose_name='口座番号')),
                ('bank_account_holder', secured_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='口座名義')),
                ('bank_account_type', models.SmallIntegerField(blank=True, choices=[(1, '普通'), (2, '当座')], null=True, verbose_name='口座の種類')),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='販売業者名')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='運営統括責任者名')),
                ('seller_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='販売業者所在地')),
                ('seller_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='販売業者電話番号')),
                ('seller_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='販売業者メールアドレス')),
                ('price_info', models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品の販売価格')),
                ('additional_fees', models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品代金以外の必要料金')),
                ('allowed_payment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='支払い方法')),
                ('delivery_method', models.TextField(blank=True, max_length=1000, null=True, verbose_name='商品の引渡方法')),
                ('return_policy', models.TextField(blank=True, max_length=1000, null=True, verbose_name='返品・不良品対応')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='データ更新日時')),
            ],
            options={
                'verbose_name_plural': '01-01. 申し込み者',
                'db_table': 'applicant',
            },
        ),
    ]
