# Generated by Django 5.0.1 on 2025-09-18 16:47

import django.db.models.deletion
import django_ckeditor_5.fields
import front.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='カテゴリ概要')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='SEOキーワード群（カンマ区切り）')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='データ更新日時')),
            ],
            options={
                'verbose_name_plural': '02-01. 記事カテゴリ',
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='データ作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='データ更新日時')),
            ],
            options={
                'verbose_name_plural': '02-02. タグ',
                'db_table': 'article_tag',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_a',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言A'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_b',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言B'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言C'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_d',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言D'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_e',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言E'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_enabled',
            field=models.BooleanField(default=0, verbose_name='スクリーンショット文言変更の希望'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_f',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言F'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='screenshot_text_g',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スクリーンショット文言G'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='store_copyright',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ストア著作権表記'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='store_description_long',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='ストア掲載用アプリ概要（詳細）'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='store_description_short',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ストア掲載用アプリ概要（短文）'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('eyecatch_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='アイキャッチタイトル')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=front.models.path_and_rename, verbose_name='アイキャッチ画像')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='本文')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='記事要約')),
                ('table_of_contents', models.TextField(blank=True, null=True, verbose_name='目次')),
                ('lead_text', models.TextField(blank=True, null=True, verbose_name='リード文')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='メタデータ')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('is_seed_generated', models.BooleanField(default=False, help_text='記事生成がレディになった時は外す。', verbose_name='タイトル・要約のみ生成済')),
                ('embedding', models.JSONField(blank=True, help_text='タイトル＋要約のベクトル表現（text-embedding-3-small）', null=True, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.articlecategory', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, to='front.articletag', verbose_name='タグ')),
            ],
            options={
                'verbose_name_plural': '02-03. 記事',
                'db_table': 'article',
            },
        ),
    ]
